# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FareTypes',
            fields=[
                ('fare_id', models.AutoField(primary_key=True, serialize=False)),
                ('fare_name', models.CharField(blank=True, max_length=20, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'fare_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('passenger_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=30, null=True)),
                ('lname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('preferred_billing_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'passengers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_date', models.DateTimeField(blank=True, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'reservations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Segments',
            fields=[
                ('segment_id', models.AutoField(primary_key=True, serialize=False)),
                ('seg_fare', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'db_table': 'segments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=40)),
                ('station_symbol', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'db_table': 'stations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False)),
                ('train_direction', models.IntegerField(blank=True, null=True)),
                ('train_days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trains',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_date', models.DateField()),
                ('fare', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'db_table': 'trips',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeatsFree',
            fields=[
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.Trains')),
                ('seat_free_date', models.DateField()),
                ('freeseat', models.IntegerField()),
            ],
            options={
                'db_table': 'seats_free',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StopsAt',
            fields=[
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.Trains')),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stops_at',
                'managed': False,
            },
        ),
    ]
